#!/usr/bin/perl

use strict;
use warnings;
use IO::File;

my $file = $ARGV[0] || die "$0 <FILE>";

my $iter = 1;

my $write_file = "Darth Bane 2, Intro.txt";
my $wfh = IO::File->new(">$write_file") or die "$@";

open(FILE, $file) or die "Can't open file: $@";
foreach my $line (<FILE>) {
    if ($line =~ m{^Chapter\ (\d+)}) {
        $write_file = sprintf("Darth Bane 2, Chapter %02d.txt", $1);
        undef $wfh;
        $wfh = IO::File->new(">$write_file") or die "$@";
        print "Writing to $write_file\n";
    }
    print $wfh $line;
}

